import axiosInstance from "@/lib/axios";

// --- Interfaces for AI Conversation ---

export interface AiMessage {
  id: string;
  role: "USER" | "AI" | "SYSTEM";
  content?: string;
  text?: string;
  provider?: string;
  model?: string;
  createdAt: string;
  pendingAction?: {
    id: string;
    actionType: string;
    description: string;
    status: 'PENDING' | 'CONFIRMED' | 'REJECTED';
  };
  generatedArtifact?: string;
  jobReference?: {
    status: 'PENDING' | 'RUNNING' | 'WAITING_RETRY' | 'COMPLETED' | 'FAILED';
  };
  citations?: string[];
  suggestedFollowups?: string[];
}

export interface ConversationItem {
  id: string;
  title: string;
  courseId?: string | null;
  applicationRoleSnapshot: string;
  archived: boolean;
  createdAt: string;
  updatedAt: string;
  messages?: AiMessage[];
}

export interface ConversationsResponse {
  items: ConversationItem[];
}

export interface CreateConversationPayload {
  title?: string;
  courseId?: string;
}

export interface SendMessagePayload {
  content: string;
  courseId?: string;
}

export interface SendMessageResponse {
  conversationId: string;
  messageId: string;
  text: string;
  status: string;
  citations: string[];
}

// --- Interfaces for Pending Actions ---

export interface ActionConfirmResponse {
  actionId: string;
  status: string;
  task: {
    id: string;
    projectId: string;
    externalId: string;
    externalKey: string;
    title: string;
    type: string;
    status: string;
    priority: string;
    storyPoint: number;
    dueDate: string;
    externalUpdatedAt: string;
    resolvedAt: string;
    resolution: string;
    description: string;
    labels: string[];
    components?: {
      id: string;
      name: string;
    }[];
    sprint?: {
      id: string;
      name: string;
      externalSprintId: string;
    };
    assignee?: {
      id: string;
      fullName: string;
      studentCode: string;
    };
    reporter?: {
      id: string;
      fullName: string;
      studentCode: string;
    };
    blocksTaskId?: string;
  };
}

export interface ActionRejectResponse {
  id: string;
  conversationId: string;
  actionType: string;
  status: string;
  summary: string;
  idempotencyKey: string;
  expiresAt: string;
  safeErrorCode: string;
  payload: Record<string, string>;
}

// --- API Client ---

export const aiAgentApi = {
  // 1. Get all conversations
  getConversations: async () => {
    return axiosInstance.get<never, ConversationsResponse>("/api/v1/ai/conversations");
  },

  // 2. Create conversation
  createConversation: async (payload: CreateConversationPayload) => {
    return axiosInstance.post<never, ConversationItem>("/api/v1/ai/conversations", payload);
  },

  // 3. Get conversation detail (includes messages)
  getConversationDetail: async (conversationId: string) => {
    return axiosInstance.get<never, ConversationItem>(`/api/v1/ai/conversations/${conversationId}`);
  },

  // 4. Send message to conversation
  sendMessage: async (conversationId: string, payload: SendMessagePayload) => {
    return axiosInstance.post<never, SendMessageResponse>(`/api/v1/ai/conversations/${conversationId}/messages`, payload);
  },

  // 5. Confirm a pending action (e.g. creating a task)
  confirmPendingAction: async (actionId: string) => {
    return axiosInstance.post<never, ActionConfirmResponse>(`/api/v1/ai/pending-actions/${actionId}/confirm`);
  },

  // 6. Reject a pending action
  rejectPendingAction: async (actionId: string) => {
    return axiosInstance.post<never, ActionRejectResponse>(`/api/v1/ai/pending-actions/${actionId}/reject`);
  },

  // 7. Download an artifact generated by AI
  downloadArtifact: async (artifactId: string) => {
    return axiosInstance.get(`/api/v1/ai/artifacts/${artifactId}/download`, {
      responseType: 'blob'
    });
  }
};
